### ISSUE TITLE
最右边单元格合并数组越界

### ISSUE THREAD

**Issue by dtgz-sudo** [qrpcode/wordgo#13]
`        // 第一页项目基本信息表格column-width:1=25%,2=25%,3=25%,4=25%;
        wordTable = new WordTable(9, 4,"font-size: 小三; font-family:仿宋;text-align:center;font-weight :bold;");
        // 合并单元格
        wordTable.merge(1,2,1,4);`
代码如上 合并单元格时如果包括最后一列 就会报错

`java.lang.IndexOutOfBoundsException: Index: 4, Size: 4

	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.github.qrpcode.util.WordFileUtilImpl.tableGridDo(WordFileUtilImpl.java:305)
	at com.github.qrpcode.util.WordFileUtilImpl.wordTableDo(WordFileUtilImpl.java:261)
	at com.github.qrpcode.domain.WordGo.add(WordGo.java:163)
	at com.github.qrpcode.domain.WordGo.addTable(WordGo.java:154)`

**Comment by error0g** [comment]
测试用例和文件发出来呗

**Comment by lkzgit** [comment]
这个问题解决了吗
