### ISSUE TITLE
插入图片报错

### ISSUE THREAD

**Issue by memorytocode** [qrpcode/wordgo#6]
java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1	
-----------------------------------------------------
at java.lang.String.substring(String.java:1927)
	at com.github.qrpcode.util.StrUtil.getImgFormat(StrUtil.java:378)
	at com.github.qrpcode.util.IoUtil.newImgAdd(IoUtil.java:155)

**Comment by memorytocode** [comment]
已解决了，哈哈
